### ISSUE TITLE
Beta - Python Error

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#168]
Not sure if this is an actual error or not, but wanted to post to find out.

```
TheTVDB.GetMetadata() - TVDBid: '337623', IMDbid: ''
common.LoadFile() - Filename: '337623.xml', Directory: 'TheTVDB\xml', url: 'http://thetvdb.plexapp.com/api/A27AD9BE0DA63333/series/337623/all/en.xml' does not exists in cache
Requesting 'http://thetvdb.plexapp.com/api/A27AD9BE0DA63333/series/337623/all/en.xml'
Exception in I/O handler for fd 1172
Traceback (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-c40bba82e\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\ioloop.py", line 256, in start
    self._handlers[fd](fd, events)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-c40bba82e\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\stack_context.py", line 128, in wrapped
    callback(*args, **kwargs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-c40bba82e\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\httpserver.py", line 219, in _handle_events
    connection, address = self._socket.accept()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 10035] A non-blocking socket operation could not be completed immediately
Handling request GET /:/plugins/com.plexapp.agents.hama/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNgoyMDM5MDJzNApkYmlkaTAKczcKdmVyc2lvbm5zMTAKcGFyZW50R1VJRG5zOApwYXJlbnRJRHM3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZXM0Ngpjb20ucGxleGFwcC5hZ2VudHMuaGFtYTovL3R2ZGIyLTMxMjY2ND9sYW5nPWVuczQKZ3VpZHMxMgp0dmRiMi0zMTI2NjRzMgppZHIwCg__
Received packed state data (1524 bytes)
Found route matching /:/plugins/com.plexapp.agents.hama/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNgoyMDM5MDJzNApkYmlkaTAKczcKdmVyc2lvbm5zMTAKcGFyZW50R1VJRG5zOApwYXJlbnRJRHM3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZXM0Ngpjb20ucGxleGFwcC5hZ2VudHMuaGFtYTovL3R2ZGIyLTMxMjY2ND9sYW5nPWVuczQKZ3VpZHMxMgp0dmRiMi0zMTI2NjRzMgppZHIwCg__
Loading model with GUID com.plexapp.agents.hama://tvdb2-312664?lang=en
Deserializing from C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Metadata\TV Shows\7\6a35802773a8b0685e79f14c52ec131bbc901c2.bundle\Contents\com.plexapp.agents.hama\Info.xml
LoadFile() - url: 'http://thetvdb.plexapp.com/api/A27AD9BE0DA63333/series/337623/all/en.xml' loaded
common.SaveFile() - CachePath: 'C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems', file: 'TheTVDB\xml\337623.xml', directory present
TheTVDB.GetMetadata() - TVDBid: '337623', IMDbid: tt7836688, url: 'http://thetvdb.com/api/A27AD9BE0DA63333/series/337623/all/en.xml'
```

**Comment by ZeroQI** [comment]
Python. Error not in my code.
Have a firewall or 'Security suite' antivirus? Look there first
Wait for Ple to update em edded python

**Comment by sven-7** [comment]
Okay, thanks.

**Comment by sven-7** [comment]
Didn't see anything in firewall or security suite that is blocking it. 

So I need to wait until Plex updates Python?

**Comment by ZeroQI** [comment]
Don't think i can prevent  [Errno 10035] A non-blocking socket operation could not be completed immediately
yeah wait for an update. if i can observe and reproduce maybe i can test things but without i cannot do much

**Comment by sven-7** [comment]
Okay, no problem.  Is this something I should report to the Plex forums?

**Comment by sven-7** [comment]
Just noticed that when getting this error, it's usually only on shows that have a tvdb 2/3/4.id file in them.  Not sure why that would be happening...

```
=== Update ==================================================================================================================================================
id: tvdb2-283925, title: Ai: Tenchi Muyo!, lang: en, force: True, movie: False
-------------------------------------------------------------------------------------------------------------------------------------------------------------
[=] originally_available_at        Sources: (TheTVDB), AniDB                                              Type: date                  Value: '2015-03-29'
AnimeLists.GetMetadata() - source: tvdb2, id: 283925, AniDB_id: , TVDB_id: 283925
[=] producers                      Sources: TheTVDB,(AniDB)                                               Type: list                  Value: 'Akao Deko'
AnimeLists.GetMetadata() - Local custom mapping - No file detected
[=] writers                        Sources: (AniDB),TheTVDB                                               Type: list                  Value: 'Terajima Yuuji'
[!] guest_stars                    Sources: None                                                          Type: SetObject             Inside : []
[=] directors                      Sources: TheTVDB,(AniDB)                                               Type: list                  Value: 'Tasaki Satoshi,Masuhara Mitsuyuki'
[=] rating                         Sources: (AniDB), TheTVDB, MyAnimeList, TheMovieDb, OMDb               Type: float                 Value: '9.94'
[=] producers                      Sources: TheTVDB,(AniDB)                                               Type: list                  Value: 'Konuta Kenji'
[=] thumbs                   ( 1)  Sources: (TheTVDB)                                                     Type: dict                  Value: '{'http://thetvdb.plexapp.com/banners/episodes/337122/6504072.jpg': ('TVDB/episodes/6504072.jpg', 1, None)}'
[!] guest_stars                    Sources: None                                                          Type: SetObject             Inside : []
[=] duration                       Sources: TheTVDB, (AniDB), MyAnimeList, TheMovieDb, OMDb               Type: int                   Value: '1500000'
[=] rating                         Sources: (AniDB), TheTVDB, MyAnimeList, TheMovieDb, OMDb               Type: float                 Value: '10.00'
[!] content_rating                 Sources: AniDB, TheTVDB                                                Type: NoneType              Inside : []
[!] thumbs                         Sources: TheTVDB                                                       Type: ProxyContainerObject  Inside : []
[!] content_rating_age             Sources: None                                                          Type: NoneType              Inside : []
Exception in I/O handler for fd 1356
Traceback (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-c40bba82e\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\ioloop.py", line 256, in start
    self._handlers[fd](fd, events)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-c40bba82e\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\stack_context.py", line 128, in wrapped
    callback(*args, **kwargs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-c40bba82e\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\httpserver.py", line 219, in _handle_events
    connection, address = self._socket.accept()
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 10035] A non-blocking socket operation could not be completed immediately
Handling request GET /:/plugins/com.plexapp.agents.hama/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IwczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZTExCnMxNgo4YzE4ZWRmOTY4YTgxY2RkczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczMKNTAxczcKZXBpc29kZW5zNApuYW1lczEKMXM4CmVwaXNvZGljczMxCkRhcmtlciBUaGFuIEJsYWNrIFt0dmRiMi04MDA0Ml1zNApzaG93czEKMHM2CnNlYXNvbm5zNAp5ZWFyczUxCkUlM0ElNUNTZXJpZXMlNUNEYXJrZXIlMjBUaGFuJTIwQmxhY2slNUNUaHVtYnMlMkVkYnM4CmZpbGVuYW1lczQwCjcyZjhjNmUyZWU3NjdhZWZiZWI0NmQzNDUwMTVmMTY1YTVhOTc0OGNzOApwbGV4SGFzaHMyCi0xczgKZHVyYXRpb25zNgoyNDEwNDNzMgppZHIwCg__
[=] duration                       Sources: TheTVDB, (AniDB), MyAnimeList, TheMovieDb, OMDb               Type: int                   Value: '1500000'
[!] absolute_index                 Sources: None                                                          Type: NoneType              Inside : ['TheTVDB']
Received packed state data (80 bytes)
-------------------------------------------------------------------------------------------------------------------------------------------------------------

```

**Comment by ZeroQI** [comment]
Whether in id file or series folder shouldn't matter
that means the scanner download the file and maybe it does it too quickly, as unlike the agent there is no check nor temporisation... 
Does it happen with libraries with 1 folder with forced id only ?
I don't know what to change and don't have the issue here
