### ISSUE TITLE
Scrobbler/TV tracker support

### ISSUE THREAD

**Issue by ZeroQI** [ZeroQI/Hama.bundle#235]
sources:
- https://www.reddit.com/r/PleX/comments/7o2te1/scrobbler_for_anime/
- https://github.com/trakt/Plex-Trakt-Scrobbler/issues/190

##Taiga
- Windows only: http://taiga.moe/
- Taiga supports dozens of media players including MPC-HC, mpv, PotPlayer, VLC and Kodi.
- streaming services support: AnimeLab, Anime News Network, Crunchyroll, HIDIVE, Plex Web App, Veoh, VIZ, VRV, Wakanim and YouTube.(supported web browsers: Google Chrome, Mozilla Firefox or Opera)

##Kitsu
- Docker VM only: https://github.com/matthewdias/kitsu-plex-scrobbler

##Trakt
- Plex agent: https://github.com/trakt/Plex-Trakt-Scrobbler
- Trakt support hama series with tvdb guid already (multiple seasons or '[tvdb-xxxxxxx]'), including tvdb2 and tvdb3 modes, but not AniDB numbered series
- sync trakt to MAL with http://txm.huere.net/ and http://txm.huere.net/import/

Since i cross reference between AniDB and TheTVDB already and check both for files present in AniDB.py and TheTVDB.py , should i support scrobbling, and to which database:
- Trakt https://github.com/trakt/Plex-Trakt-Scrobbler
- MyAnimeList (anidb xml gives me the ANNid and MALid already) and it seem the best and most popular...
- Simkl https://simkl.com / https://simkl.docs.apiary.io/#introduction/about-simkl-api/use-cases (pays 200$, code for auth already done)
- AniDB
- AniList https://anilist.co/
- Filmsomniac https://www.filmsomniac.com/

**Comment by Xalaxis** [comment]
Please work further on supporting the Trakt Plex scrobbler initially.  Sometimes series do not scrobble, and I'm assuming Hama matching on another attribute (and thus this lack of support) is the most likely cause?

**Comment by Xalaxis** [comment]
Would you suggest manually assigning a TVDB GUID to all 1 season shows I want to scrobble correctly?  I've migrated from MAL after their API hack. (Also, I like having all my shows in one place)

**Comment by Xalaxis** [comment]
As for scrobbling from Hama itself, I think personally that might be overstepping the role of the agent.  Ideally a server should always do it's own scrobbling through the use of plugins.

Perhaps if you wish to support scrobbling you could implement it as a plugin?

**Comment by ZeroQI** [comment]
@Xalaxis you could but that might have complications for specials.
I see your point, but Hama is suited to take anidb numbered series and update in thetvdb transparently at the right season and ep number, the logic is already there and the ep presence checks too...
If i were to separate, i would have to re-download the mapping file

What i am considering as external agent is an agent to export into an nfo and import and also save series and season poster, ep thumb, etc...

**Comment by purposelycryptic** [comment]
AniDB scrobbling would be awesome, as the only way I know if doing that currently is running Shoko, and using the ShokoMetadata Agent for Plex, which still has a lot of issues due to having to go through the Shoko API, and isn't seeing much active development. It's not built around scrobbling, so I'm not sure if the API would cause issues (I think Shoko only periodically updates the watched states, rather than scrobbling at time of play, but not 100%), but it would definitely be a great addition.

Integrated Trakt scrobbling would certainly solve a lot of the issues with Trakt when using the AniDB style organisation.

MAL is currently in limbo, with their new API up in the air, to the point that the Shoko devs have completely given up on it and have been removing all the old code references to it - making anything for the current API would likely be a waste as it is getting replaced, and from what I've gathered from Shoko's devs, the folks at MAL are being fairly hostile and uncooperative when it comes to their new API development (hence why they've abandoned it).

Taiga works with both AniList and Kitsu (and, up until the fall of MAL, MAL as well), but can only work with one of them at a time. Currently, it only works with the Plex Web Interface and Plex Home Theater, but Plex Media Player appears to be the next platform they are looking to get working. They use their own file identification system to match what is currently being played with the entries on the particular service.

**Comment by Xalaxis** [comment]
@purposelycryptic @ZeroQI I'm in contact with one of the developers for the Trakt-sync plugin right now and apparently it *is* supposed to handle AniDB matching through the use of a conversion XML.  I'm currently discussing why this doesn't seem to be working for me.  This should be a good alternative for those who do want to sync single season shows without any changes required here.

**Comment by ZeroQI** [comment]
@Xalaxis it may base itself on anidbid as the metadata.id but i use anidb-xxxxx, tvdb-xxxxx, tvdb2-xxxxxx, tvdb3-xxxxxxx and they already support tvdb. if anidb is meant to work take a series that down't work, reproduce and interract with Trakt-sync. and i am availlable to discuss with them to assist if there is any need as this would help tremendously Plex Anime watchers, and boost adoption rate of Trakt as there is nothing really working for anime sine MyAnimeList API went under...

**Comment by Xalaxis** [comment]
@ZeroQI I have managed to solve my local problems with the Trakt maintaners and I can confirm that the plugin should indeed be syncing AniDB-matched shows across.

If any users notice this is not the case, then it is not intentional behaviour provided the mappings at https://github.com/fuzeman/anime-lists/blob/master/anime-list-master.xml are up to date.  @fuzeman has now implemented automatic updates from ScuddLee's upstream lists at https://github.com/ScudLee/anime-lists/blob/master/anime-list-master.xml so this process should go faster than it has in the past.

**Comment by purposelycryptic** [comment]
@Xalaxis I went over the past 2 weeks of my Trakt log, and it was correct for everything except two specials that had not yet been mapped in ScuddLee's _anime-list-master.xml_ (The latest two Shingeki no Kyojin OVAs), which got a false positive as s01e06-s01e07 instead of s00e06-s00e07 - which seems like an expected result, as they only had mapping info in my local HAMA _anime-list-master.xml_ and _anime-list-custom.xml_.

While I can't say whether it now works perfectly, those 2 weeks represent a sample of 108 episodes from series ranging from 2006 to currently airing, for which the plugin demonstrated an effective 100% accuracy rate, with no missing or misidentified episodes outside of the two mentioned above, the misidentification of which was not caused by the plugin itself. I did a side-by-side comparison with my viewing log in Tautulli, just to make sure nothing was missing.

Compared to its previous performance, where it would frequently miss (or misidentify) entire series, it's a whole world of difference, so, barring some random drastic error suddenly rearing its head, I would say the plugin now properly does anime :-)

**Comment by ZeroQI** [comment]
@Xalaxis Excellent news for all users. Do you know the difference between scudlee and fuzeman anime-lists? fuzeman seem more up to date but can't find any mention of it...

**Comment by Xalaxis** [comment]
@ZeroQI I believe @fuzeman's list is essentially a clone of ScuddLee's list, to allow for changes specific to the Trakt-Plex-scrobbler to be changed independently (and potentially changes to the format made in the future if required).  That way if ScuddLee's list suddenly changes in an unexpected way, the scrobbler can be kept working until a solution is developed.

ScuddLee's is where any mapping changes should be requested in the first instance.

**Comment by ZeroQI** [comment]
Excellent information on that post.
Closing as currently working with Trakt

**Comment by RickDB** [comment]
@Xalaxis Having some issues with Trakt scrobbler and wondering if you noticed the same before.

Problem is it won't scrobble or sync any Anime with the the latest version of the Trakt Plex plugin and HAMA, it will report that it can't match it properly and errors out during below scrobble for instance:

```
2018-11-07 19:29:22,703 - plugin.modules.mapper.main       (8160) :  WARNING (plugin.modules.mapper.main:209) - Unable to retrieve mapping for 13259 (anidb -> tvdb) - unpack requires a string argument of length 10
Traceback (most recent call last):
  File "C:\Users\Rick\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\plugin\modules\mapper\main.py", line 203, in map
    resolve_mappings=resolve_mappings
  File "C:\Users\Rick\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\oem_client_anidb\main.py", line 54, in map
    item = self.get(key)
  File "C:\Users\Rick\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\oem_client_anidb\main.py", line 35, in get
    if not self.fetch(key, metadata):
  File "C:\Users\Rick\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\oem_framework\core\elapsed.py", line 119, in wrapper
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "C:\Users\Rick\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\oem_framework\core\elapsed.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Rick\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\oem\core\services\base.py", line 89, in fetch
    key, metadata
  File "C:\Users\Rick\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\oem_client_provider_release\incremental.py", line 40, in fetch
    if not self.update_item(source, target, version, key, metadata):
  File "C:\Users\Rick\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\oem_client_provider_release\incremental.py", line 170, in update_item
    if self.storage.has_item(source, target, key, metadata):
  File "C:\Users\Rick\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\oem_storage_codernitydb\main.py", line 235, in has_item
    item = self.database.get('item_key', (source, target, key), with_doc=True)
  File "C:\Users\Rick\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\CodernityDB\database_super_thread_safe.py", line 43, in _inner
    res = f(*args, **kwargs)
  File "C:\Users\Rick\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\CodernityDB\database.py", line 940, in get
    l_key, _unk, start, size, status = ind.get(key)
  File "C:\Users\Rick\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\CodernityDB\tree_index.py", line 1850, in get
    return self._find_key(self.make_key(key))
  File "C:\Users\Rick\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\CodernityDB\rr_cache.py", line 34, in wrapper
    cache1lvl[key] = user_function(key, *args, **kwargs)
  File "C:\Users\Rick\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\CodernityDB\tree_index.py", line 1528, in _find_key
    nr_of_elements, prev_leaf, next_leaf = self._read_leaf_nr_of_elements_and_neighbours(containing_leaf_start)
  File "C:\Users\Rick\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\CodernityDB\rr_cache.py", line 34, in wrapper
    cache1lvl[key] = user_function(key, *args, **kwargs)
  File "C:\Users\Rick\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\CodernityDB\tree_index.py", line 193, in _read_leaf_nr_of_elements_and_neighbours
    data)
error: unpack requires a string argument of length 10
2018-11-07 19:29:22,704 - plugin.scrobbler.methods.core.base (8160) :  INFO (plugin.scrobbler.methods.core.base:62) - Unable to build request for session: <Session session_key: u'60:72', state: 'stop'>
```

No clue why yet and debugging it further but if you have any idea would appreciate it.

**Comment by Xalaxis** [comment]
@RickDB Try setting Logging - Libraries to DEBUG if not already set, (In the Trakt settings) and then looking for lines near:

`Loaded service: anidb ->`

I'm wondering if the plugin is having issues receiving the latest anime mappings updates.

I haven't personally experienced anything like the errors you've had above unfortunately 🙁

**Comment by RickDB** [comment]
Enabled debug and seems the service is loaded:

```
2018-11-08 00:43:03,548 - plugin.sync.modes.core.base.mode (2f468) :  INFO (plugin.sync.modes.core.base.mode:127) - Executing start() on child: <plugin.sync.modes.push.movies.Movies object at 0x05F94E50>
2018-11-08 00:43:03,549 - plugin.sync.modes.core.base.mode (2f468) :  INFO (plugin.sync.modes.core.base.mode:127) - Executing start() on child: <plugin.sync.modes.push.shows.Shows object at 0x05F30A10>
2018-11-08 00:43:03,956 - plugin.sync.modes.core.base.mode (2f468) :  INFO (plugin.sync.modes.core.base.mode:127) - Executing run() on child: <plugin.sync.modes.push.movies.Movies object at 0x05F94E50>
2018-11-08 00:43:03,957 - plugin.sync.modes.core.base.mode (2f468) :  INFO (plugin.sync.modes.core.base.mode:127) - Executing run() on child: <plugin.sync.modes.push.shows.Shows object at 0x05F30A10>
2018-11-08 00:43:03,957 - plex_metadata.agents.main        (2f468) :  DEBUG (plex_metadata.agents.main:18) - Compiling agents...
2018-11-08 00:43:03,957 - plex_metadata.agents.main        (2f468) :  DEBUG (plex_metadata.agents.main:25) - Compiled 23 agents
2018-11-08 00:43:03,961 - requests.packages.urllib3.connectionpool (2f468) :  DEBUG (requests.packages.urllib3.connectionpool:810) - Starting new HTTPS connection (1): api.github.com
2018-11-08 00:43:04,391 - requests.packages.urllib3.connectionpool (2f468) :  DEBUG (requests.packages.urllib3.connectionpool:401) - https://api.github.com:443 "GET /repos/OpenEntityMap/oem-database-anidb-tmdb-movie/releases/latest HTTP/1.1" 403 None
2018-11-08 00:43:04,395 - oem_client_provider_release.incremental (2f468) :  INFO (oem_client_provider_release.incremental:84) - Unable to find database 'OpenEntityMap/oem-database-anidb-tmdb-movie', will retry in 3600 seconds
2018-11-08 00:43:04,395 - oem.core.services.base           (2f468) :  INFO (oem.core.services.base:74) - Loaded service: anidb -> tmdb:movie (storage: <oem_storage_codernitydb.database.DatabaseCodernityDbStorage object at 0x069F07B0>)
2018-11-08 00:43:04,398 - requests.packages.urllib3.connectionpool (2f468) :  DEBUG (requests.packages.urllib3.connectionpool:810) - Starting new HTTPS connection (1): api.github.com
2018-11-08 00:43:04,871 - requests.packages.urllib3.connectionpool (2f468) :  DEBUG (requests.packages.urllib3.connectionpool:401) - https://api.github.com:443 "GET /repos/OpenEntityMap/oem-database-anidb-imdb/releases/latest HTTP/1.1" 403 None
2018-11-08 00:43:04,875 - oem_client_provider_release.incremental (2f468) :  INFO (oem_client_provider_release.incremental:84) - Unable to find database 'OpenEntityMap/oem-database-anidb-imdb', will retry in 3600 seconds
2018-11-08 00:43:04,875 - oem.core.services.base           (2f468) :  INFO (oem.core.services.base:74) - Loaded service: anidb -> imdb  (storage: <oem_storage_codernitydb.database.DatabaseCodernityDbStorage object at 0x069F0650>)
2018-11-08 00:43:04,878 - requests.packages.urllib3.connectionpool (2f468) :  DEBUG (requests.packages.urllib3.connectionpool:810) - Starting new HTTPS connection (1): api.github.com
2018-11-08 00:43:05,292 - requests.packages.urllib3.connectionpool (2f468) :  DEBUG (requests.packages.urllib3.connectionpool:401) - https://api.github.com:443 "GET /repos/OpenEntityMap/oem-database-anidb-tvdb/releases/latest HTTP/1.1" 403 None
2018-11-08 00:43:05,296 - oem_client_provider_release.incremental (2f468) :  INFO (oem_client_provider_release.incremental:84) - Unable to find database 'OpenEntityMap/oem-database-anidb-tvdb', will retry in 3600 seconds
2018-11-08 00:43:05,296 - oem.core.services.base           (2f468) :  INFO (oem.core.services.base:74) - Loaded service: anidb -> tvdb  (storage: <oem_storage_codernitydb.database.DatabaseCodernityDbStorage object at 0x069F0D70>)
2018-11-08 00:43:05,296 - plugin.sync.modes.push.shows     (2f468) :  INFO (plugin.sync.modes.push.shows:115) - Unable to find identifier for: anidb/10934 (rating_key: 34816)
2018-11-08 00:43:05,298 - plugin.sync.modes.push.shows     (2f468) :  INFO (plugin.sync.modes.push.shows:115) - Unable to find identifier for: anidb/10813 (rating_key: 37890)
2018-11-08 00:43:05,299 - plugin.sync.modes.push.shows     (2f468) :  INFO (plugin.sync.modes.push.shows:115) - Unable to find identifier for: anidb/8357 (rating_key: 36868)
2018-11-08 00:43:05,299 - plugin.sync.modes.push.shows     (2f468) :  INFO (plugin.sync.modes.push.shows:115) - Unable to find identifier for: anidb/1312 (rating_key: 34821)
2018-11-08 00:43:05,299 - plugin.sync.modes.push.shows     (2f468) :  INFO (plugin.sync.modes.push.shows:115) - Unable to find identifier for: anidb/6227 (rating_key: 37895)
```

Will try on a fresh test server and see what it does there, thanks for the quick response and pointers :)

**Comment by RickDB** [comment]
OpenEntityMap removed the releases so that explains the 403 error, not sure about an easy fix as this is on the Trakt side.
